### ISSUE TITLE
Question: Random Timeout between Actions

### ISSUE THREAD

**Issue by LuckLP** [alextruong2600/energyairbot2021#1]
Ich weiss nicht, ob die keine Erkennung haben, ob ein Bot das Quiz ausführt.

Wenn sie eine haben, wirst du wahrscheinlich ganz schnell im System geflaggt. 

Die Frage ist, ob es sich lohnt einen Random Timer einzubauen?

**Comment by alextruong2600** [comment]
Danke für den Hinweis und die Idee. Ich habe mit dem Bot auch schon Tickets gewonnen, aber ich werde einen Random Timer einbauen und schauen wie es sich dann verhält.

**Comment by LuckLP** [comment]
Also du hast damit schon Tickets geholt?

**Comment by alextruong2600** [comment]
Ja genau habe auch schon Tickets damit gewonnen. Habe den Code jetzt schon angepasst und einen Random Timer eingebaut. Das System erkennt jedoch sehr wahrscheinlich, ob eine Tel Nummer schon mal im Game gewonnen hat und dadurch kann man nur einmal pro Nummer gewinnen. Mehrfachgewinne sind von Seitens Energy ausgeschlossen; Zitat: _"Energy behält sich jedoch das Recht vor, Mehrfachgewinne zu ignorieren und pro Mitspieler nur einmal den gleichen Preis auszuhändigen."_

**Comment by Markymarc14** [comment]
Die Logoauswahl und neustart geht bei mir nicht

**Comment by alextruong2600** [comment]
Bin den Code am bearbeiten, es kann noch einige bugs geben.

**Comment by alextruong2600** [comment]
Die Logoauswahl funktioniert nur am PC, bzw. am Laptop. Du must das Fenster Maximieren, damit es funktioniert.

**Comment by RoadJDK** [comment]
Braucht es bei dir auch nur etwa 2 Sekunden, für einen Rundgang?
Ausserdem sieht man nur kurz das aufmachen, aber nie das Ergebnis?

**Comment by alextruong2600** [comment]
Danke für den Hinweis. Der Code hat noch einige Bugs, die ich am fixen bin. Schreibe wenn alles tip top funktioniert

**Comment by alextruong2600** [comment]
@RoadJDK  und @Markymarc14 
Ich habe den Code überarbeitet. Pro Frage benötigt der Bot zwischen 1.2 bis 2 Sekunden. Nach der Auswahl des Logos seht ihr nun etwa 2 bis 3 Sekunden lang, ob Ihr gewonnen habt. Wenn Ihr gewonnen habt, bekommt Ihr ein SMS auf eure Nummer mit dem Link zu den Tickets.

**Comment by Markymarc14** [comment]
Scheint zu laufen. Danke Dir.

**Comment by Markymarc14** [comment]
Gibt wohl ne neue frage. Die ist auf jedenfall nicht so aufgeführt

**Comment by Xaendu123** [comment]
Ich habe ziemlich schnell Tickets gewonnen, gewinne aber seit 2 Tagen nichts mehr. Auch mit unterschiedlichen Accounts. Sieht aus als wäre ich gflagged worden. Die Frage ist: weiss jemand wie lange oder wie ich es umgehen kann?

**Comment by alextruong2600** [comment]
Kann es sein, dass du mit anderen accounts spielst, jedoch immer die gleiche Handynummer angiebst? Energy schenkt jeder Handynummer im Game nur ein Mal Tickets. Mehrfachgewinne können von Energy  automatisch gesperrt werden.

**Comment by Xaendu123** [comment]
Nein leider nicht. Es sind leider komplett  unterschiedliche Accounts.. kann sein, dass es nur Pech ist aber das halte ich nicht für sehr wahrscheinlich.

**Comment by alextruong2600** [comment]
Okey... Eigentlich solltest du mit diesem Code nicht geflagged werden. Ich werde mir den Code nochmals anschauen und überlegen an was es liegen könnte. Das Game ist so programmiert, dass es höchstens alle 10 Min. einen Gewinn gibt. Spielen jedoch sehr viele Leute mit, so kann sich dies sogar noch erhöhen und es gibt nur alle 15, 20 oder sogar 30 Minuten einen Gewinn. Dies lässt sich leider nicht steuern.

**Comment by alextruong2600** [comment]
Was ich dir auch anraten kann ist mal nach Session Box zu googlen. Damit kannst du mit mehreren Accounts gleichzeitg spielen. Dies erhöht deine Gewinnchance.

**Comment by alextruong2600** [comment]
Mit flagging kenne ich mich auch nicht so gut aus. Ich habe bei mir mit 2 Accounts insgesammt 2 mal gewonnen. Habe aber es aber mehr als 3 Tage laufen lassen. Sonnst kannst du es auf einem anderen Gerät versuchen.

**Comment by Xaendu123** [comment]
Top danke für die schnellen Antworten! Melde mich, falls ich gewinne :)
