### ISSUE TITLE
In welchem Schweizer Kanton eröffnete Tally Weijl 1987 den ersten Store?

### ISSUE THREAD

**Issue by AVREOS** [alextruong2600/energyairbot2021#2]
Frage In welchem Schweizer Kanton eröffnete Tally Weijl 1987 den ersten Store? wird nicht automatisch ausgefüllt

**Comment by alextruong2600** [comment]
Vielen Dank für die Info. Diese Frage wurde erst heute von Energy aufgeschlatet. Ich werde dies heute Abend einfügen
