### ISSUE TITLE
Frage neu geschrieben

### ISSUE THREAD

**Issue by AVREOS** [alextruong2600/energyairbot2021#5]
Heyy, die Frage zur Swisscom Initiative wurde umgeschrieben zu "WIE HEISST DIE INITIATIVE FÜR MEHR RESPEKT IM INTERNET, WELCHE SWISSCOM MIT ENERGY LANCIERT HAT UND AM ENERGY AIR IHREN GROSSEN HÖHEPUNKT FEIERT?" habe sie bei mir im Code geändert und trotzdem schafft der Bot nicht sie auszufüllen. wollte kurz fragen ob du dies Fixen könntest da ich es nicht hinkriege, 

Beste Grüsse und danke das du den Bot bereitstellst

**Comment by AVREOS** [comment]
Habe den Fehler gefunden die Antwort wurde zu "Mute the Hate" (H bei Hate gross) geändert

**Comment by alextruong2600** [comment]
Vielen Dank für die Info. Habe es schön geändert ✌🏻
