### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by blackdiamond9** [alextruong2600/energyairbot2021#6]
Seit 2-3 Tagen wird ein Captcha verlangt. Bereits auf zwei verschiedenen Geräten & Accounts getestet. Kannst du helfen?

**Comment by ggmanugg** [comment]
Hier gibt es eine Version mit dem reCAPTCHA bypass. Funktioniert aber immer nur eine gewisse Zeit lang, bis Google es bemerkt. Danach musst du ein wenig warten bevor du das Script wieder starten kannst.

https://github.com/ggmanugg/energyair_bot
